FROM alpine:edge

RUN apk update && apk upgrade

# Install opensmtpd
COPY prefix/libexec /usr/libexec
COPY prefix/sbin /usr/sbin

# Install required software and deps
RUN apk add openssl curl dovecot-lmtpd dkimproxy libevent libasr fts libressl

VOLUME ["/data"]
EXPOSE 25/tcp
EXPOSE 587/tcp
EXPOSE 993/tcp

COPY config /root/config
CMD /root/config/config_gen.sh
