FROM alpine:edge

RUN apk update && apk upgrade

# Install opensmtpd
COPY prefix/libexec /usr/libexec
COPY prefix/sbin /usr/sbin

# Install required software
RUN apk add openssl curl dovecot-lmtpd dkimproxy
# Install deps
RUN apk add libevent libasr fts libressl

VOLUME ["/data"]

COPY config /root/config
CMD /root/config/config_gen.sh
